//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project__Hotel_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rooms
    {
        public int room_id { get; set; }
        public string room_number { get; set; }
        public string room_type { get; set; }
        public string room_availability { get; set; }
    }
}
